### PR TITLE
Server

### PR DESCRIPTION
**Pull request by ryanl-ee**
I added some spec tests for full "kitchen test" integration, tweaked the .kitchen.yml to avoid having to run 'apt-get update' on the Ubuntu box, switched out the Windows box for the newer 2012 R2 box (I couldn't get test-kitchen to correctly converge on the 2008 R2 box), separated the attributes out between client and server, and added a server recipe to install on Windows.

### CODE REVIEW

**Comment by ryanl-ee** [comment]
Also, I was able to run "kitchen test" and have all tests succeed automatically.

**Comment by lancepowell** [comment]
excellent, i'll kitchen test myself and get this merged.

**Comment by lancepowell** [comment]
I've been fighting a converge issue that i'm still working through

```
-----> Starting Kitchen (v1.4.2)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: ['' did not contain a valid
 version string: 'x.y.z' or 'x.y'.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by ryanl-ee** [comment]
Weird. I just tried `kitchen test` again and it passed.

```
C:\> chef -v
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

**Comment by lancepowell** [comment]
Ya, it's my new windows 10 update thats breaking it. I have another
computer i can test it on, i'll get there.

**Comment by lancepowell** [comment]
Merging. Only issue i can see is a warning that we can look at later:

WARN: http://iweb.dl.sourceforge.net/project/filezilla/FileZilla Server/0.9.53/FileZilla_Server-0_9_53.exe was an invalid URI.

**Pull request merged**
